@echo off
set DB_NAME=labeldb
echo Importation de artistes.json...
mongoimport --db %DB_NAME% --collection artistes --file json/artistes.json --jsonArray
echo Importation de album.json...
mongoimport --db %DB_NAME% --collection albums --file json/album.json --jsonArray
echo Importation de musique.json...
mongoimport --db %DB_NAME% --collection musique --file json/musique.json --jsonArray
echo Importation de groupes.json...
mongoimport --db %DB_NAME% --collection groupes --file json/groupes.json --jsonArray
echo Importation de manager.json...
mongoimport --db %DB_NAME% --collection manager --file json/manager.json --jsonArray
echo Importation de producteur.json...
mongoimport --db %DB_NAME% --collection producteur --file json/producteur.json --jsonArray
echo Importation terminée.
pause